---
title: "Benchmarking chk"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking chk}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```

```{r setup}
library(chk)
library(microbenchmark)
```

```{r}

fun_checking <- function(x, ...) {
  chk_flag(x)
  chk_unused(...)  
  x
}

fun_checking_global <- function(x, ...) {
  if(is_chk_on()) {
    chk_flag(x)
    chk_unused(...)
  }
  x
}

fun_checking_arg <- function(x,  chk = TRUE) {
  if(chk) {
    chk_flag(x)
  }
  x
}

wrapper_on_fun_checking <- function(x) {
  fun_checking(x)
}

wrapper_on_fun_checking_global <- function(x) {
  if(is_chk_on()) {
    chk_off()
    on.exit(chk_on())
  }
  fun_checking_global(x)
}

wrapper_on_fun_checking_arg <- function(x, chk = TRUE) {
  fun_checking_arg(x, chk = chk)
}
```

```{r}
chk_on()
microbenchmark(
  wrapper_on_fun_checking(TRUE),
  wrapper_on_fun_checking_global(TRUE),
  wrapper_on_fun_checking_arg(TRUE)
)

chk_off()
microbenchmark(
  wrapper_on_fun_checking(TRUE),
  wrapper_on_fun_checking_global(TRUE),
  wrapper_on_fun_checking_arg(TRUE, chk = FALSE)
)
```


```{r}
true <- TRUE
false <- FALSE
one <- 1
oneL <- 1L
string <- "1"
date <- as.Date(1, origin = as.Date("1970-01-01"))
datetime <- as.POSIXct(1, origin = as.Date("1970-01-01"))
null <- NULL
named <- c("1" = 1)
fun <- function() NULL
data <- data.frame(one = one)
```

```{r}
microbenchmark(
  chk_true(true),
  chk_false(false),
  chk_flag(true),
  chk_lgl(true),
  chk_number(oneL),
  chk_number(one),
  chk_whole_number(oneL),
  chk_whole_number(one),
  chk_string(string),
  chk_date(date),
  chk_datetime(datetime),
  chk_whole_numeric(oneL),
  chk_whole_numeric(one),
  chk_no_missing(one),
  chk_unique(one),
  chk_unique(data),
  chk_unique(data, incomparables = NA),
  chk_null(null),
  chk_not_null(one),
  chk_named(named),
  chk_unused(),
  chk_used(one),
  chk_function(fun),
  chk_s3_class(one, "numeric"),
  chk_identical(one, one),
  chk_equal(one, one),
  chk_equivalent(one, one),
  chk_lt(one, 2),
  chk_lte(one, one),
  chk_gt(one, 0),
  chk_gte(one, one),
  chk_range(one),
  chk_subset(one, one),
  chk_superset(one, one),
  chk_match(string),
  chk_all(true, chk_true),
  chkor(),
  chkor(chk_number(one)),
  chkor(chk_number(one), chk_proportion(one))
)
```
