context("chk-length")

test_that("chk_length", {
  expect_true(chk_length(1))
  expect_true(chk_length(1:3))
  expect_true(chk_length(numeric(0), 0L))
  expect_true(chk_length(1, c(1,2,3)))
  expect_false(chk_length(numeric(0), err = FALSE))
  expect_error(chk_length(numeric(0)), 
               "^`numeric[(]0[)]` must be length 1 to 2147483647, not length 0[.]$")
  expect_error(chk_length(1, 0), "^`1` must be length 0, not length 1[.]$")
  expect_false(chk_length(1, 0, err = FALSE))
  expect_error(chk_length(1, 2), "^`1` must be length 2, not length 1[.]$")
  expect_false(chk_length(1, c(3,2,2), err = FALSE))
  expect_true(chk_length(1, c(0,2)))
  expect_true(chk_length(1, c(2,0)))
  expect_error(chk_length(1, c(3,2,2)), "^`1` must be length 3 or 2, not length 1[.]$")
  expect_false(chk_length(1, c(2,4,3), err = FALSE))
  expect_error(chk_length(1, c(2,4,3)), "^`1` must be length 2, 4 or 3, not length 1[.]$")
  expect_error(chk_length(character(0), 1:10), "^`character[(]0[)]` must be length 1, 2, 3, 4, 5, 6, 7, 8, 9 or 10, not length 0[.]$")
  expect_error(chk_length(character(0), 1:11), "^`character[(]0[)]` must be length 1, 2, 3, 4, 5, 6, 7, 8, ... or 11, not length 0[.]$")
})
