context("chk-unique")

test_that("chk_unique", {
  expect_true(chk_unique(integer(0)))
  expect_true(chk_unique(NA))
  expect_true(chk_unique(1))
  expect_true(chk_unique(c(1,2)))
  expect_true(chk_unique(c(1,NA)))
  expect_false(chk_unique(c(NA,NA), err = FALSE))
  expect_true(chk_unique(c(NA,NA), incomparables = NA))
  expect_true(chk_unique(c(NA,NA,1), incomparables = NA))
  expect_false(chk_unique(c(1,1), err = FALSE))
  expect_false(chk_unique(c(1,2,1), err = FALSE))
  expect_error(chk_unique(c(1,1)), "^`c[(]1, 1[)]` must be unique[.]$")
  expect_error(chk_unique(c(1,1), x_name = "unicorn"), "^unicorn must be unique[.]$")
})

test_that("chk_unique data frame", {
  data <- data.frame(x = 1:2)
  expect_true(chk_unique(data))
  expect_true(chk_unique(data, incomparables = NA))
  data <- data.frame(x = c(1,1))
  expect_false(chk_unique(data, err = FALSE))
  expect_false(chk_unique(data, incomparables = NA, err = FALSE))
  data <- data.frame(y = c(NA, NA))
  expect_error(chk_unique(data), "^`data` must be unique[.]$")
  expect_true(chk_unique(data, incomparables = NA))
  data <- data.frame(x = 1:2, y = c(NA, NA))
  expect_true(chk_unique(data))
  expect_true(chk_unique(data, incomparables = NA))
  data <- data.frame(x = c(1,1), y = c(2, 2))
  expect_error(chk_unique(data), "^`data` must be unique[.]$")
  expect_true(chk_unique(data, incomparables = 2))
  data <- data.frame(x = c(1,1), y = c(NA, NA))
  expect_error(chk_unique(data), "^`data` must be unique[.]$")
  expect_true(chk_unique(data, incomparables = NA))
})

test_that("chk_no_missing", {
  expect_true(chk_no_missing(1))
  expect_true(chk_no_missing(integer(0)))
  expect_false(chk_no_missing(NA, err = FALSE))
  expect_false(chk_no_missing(c(NA, 1), err = FALSE))
  expect_error(chk_no_missing(NA), "^`NA` must not have missing values[.]$")
  expect_error(chk_no_missing(NA, x_name = "1"), "^1 must not have missing values[.]$")
})

test_that("chk_named", {
  expect_false(chk_named(list(), err = FALSE))
  expect_false(chk_named(list(1), err = FALSE))
  expect_true(chk_named(list(x = 1)))
  expect_true(chk_named(list(x = 1)[-1]))
  expect_true(chk_named(c(x = 1)))
  expect_true(chk_named(c(x = 1)[-1]))
  expect_error(chk_named(1), "^`1` must be named[.]$")
  expect_error(chk_named(1, x_name = "new born"), "^new born must be named[.]$")
})
