name: R-CMD-check
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  R-CMD-check:
    uses: poissonconsulting/.github/.github/workflows/R-CMD-check.yaml@v1
    with:
      tier: cran
      jags: false
      cmdstan: false
      tex: false
      private: false
    secrets: inherit
